### ISSUE TITLE
Can't start main.py

### ISSUE THREAD

**Issue by Knaky41** [Minims/SomfyProtect2MQTT#119]
Hi, I've cloned the code and modified the config file but when I want to execute, I've the following error:

> root@home-antoine:/opt/SomfyProtect2MQTT/somfyProtect2Mqtt# python3 main.py
Traceback (most recent call last):
  File "/opt/SomfyProtect2MQTT/somfyProtect2Mqtt/main.py", line 17, in <module>
    from somfy_protect.websocket import SomfyProtectWebsocket
  File "/opt/SomfyProtect2MQTT/somfyProtect2Mqtt/somfy_protect/websocket/__init__.py", line 12, in <module>
    from business.streaming.camera import VideoCamera
  File "/opt/SomfyProtect2MQTT/somfyProtect2Mqtt/business/streaming/camera.py", line 4, in <module>
    import cv2
  File "/usr/local/lib/python3.11/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.11/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

--

Do you know what I should do? Requirements are ok...

**Comment by Knaky41** [comment]
Solved by `apt install libgl1-mesa-glx`

**Comment by Knaky41** [comment]
Now i've another issue to start MQTT :

`root@home-antoine:/opt/SomfyProtect2MQTT/somfyProtect2Mqtt# python3 main.py -c config/config.yaml
2023-09-04 18:35:18,018 [INFO] [__main__:55] Starting SomfyProtect2Mqtt 2023.9.1
2023-09-04 18:35:18,019 [INFO] [root:41] Reading config file config/config.yaml
2023-09-04 18:35:18,028 [INFO] [root:111] Init SSO
2023-09-04 18:35:18,029 [INFO] [root:91] Init MQTT
Traceback (most recent call last):
  File "/opt/SomfyProtect2MQTT/somfyProtect2Mqtt/main.py", line 61, in <module>
    MQTT_CLIENT = init_mqtt(config=CONFIG, api=API)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/SomfyProtect2MQTT/somfyProtect2Mqtt/mqtt/__init__.py", line 95, in init_mqtt
    mqtt_client = MQTTClient(config=mqtt_config, api=api)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/SomfyProtect2MQTT/somfyProtect2Mqtt/mqtt/__init__.py", line 28, in __init__
    self.client.connect(config.get("host", "127.0.0.1"), config.get("port", 1883), 60)
  File "/usr/local/lib/python3.11/dist-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
`


my config file is:

# Somfy Protect APP credentials
somfy_protect:
  username: "bla@blabla.net"
  password: "blablabla"

  # Zones Label to check
  sites:
    - Maison

# Home Assistant Configuration
homeassistant_config:
  # Code to arm/disarm, Remove code to disable.
  code: 0607
  # Use Code on arm/disarm
  code_arm_required: false
  code_disarm_required: true

# MQTT Configuration
mqtt:
  host: 192.168.1.54
  port: 1883  # prefer SSL port if you can (not managed for now)
  username: user
  password: "blablabla"
  client-id: somfy-protect
  topic_prefix: "somfyProtect2mqtt"
  ha_discover_prefix: "homeassistant"

# SomfyProtect2MQTT
delay_site: 10  # seconds
delay_device: 60  # seconds
manual_snapshot: false


Am I doing something wrong?

**Comment by Minims** [comment]
Hello,

try to install this

ˋ``
apt-get update && apt-get install libgl1
ˋˋ`

**Comment by Minims** [comment]
Is it normal the log says mqtt connexion to 127.0.0.1 ans the config file says 192.168.1.54

Mqtt connexion is ok from this server ?

**Comment by Knaky41** [comment]
All good thanks. A short tutorial if someone wants to install a Mosquitto: https://www.howtoforge.com/how-to-install-mosquitto-mqtt-message-broker-on-debian-11/
