### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by birse29** [Minims/SomfyProtect2MQTT#125]
Hello,

I am facing this issue with the latest version of the docker image

Traceback (most recent call last):
  File "/app/main.py", line 17, in <module>
    from somfy_protect.websocket import SomfyProtectWebsocket
  File "/app/somfy_protect/websocket/__init__.py", line 12, in <module>
    from business.streaming.camera import VideoCamera
  File "/app/business/streaming/camera.py", line 4, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by Minims** [comment]
Need to dig i have never user the Docker image i build

**Comment by ScratMan** [comment]
Same issue here.

**Comment by Minims** [comment]
I have push a new build, Can you try the lastest version ?

**Comment by ScratMan** [comment]
Still thé same issue on :latest

**Comment by davic80** [comment]
New pull request should solve, I haven't build the image though
https://github.com/Minims/SomfyProtect2MQTT/pull/126

**Comment by Minims** [comment]
Issue is on armv7l i have remove this platform for now. Can you try again ?

**Comment by ScratMan** [comment]
> Issue is on armv7l i have remove this platform for now. Can you try again ?

Hello, now the error comes from another missing module.

```
Traceback (most recent call last):
  File "/app/main.py", line 17, in <module>
    from somfy_protect.websocket import SomfyProtectWebsocket
  File "/app/somfy_protect/websocket/__init__.py", line 12, in <module>
    from business.streaming.camera import VideoCamera
  File "/app/business/streaming/__init__.py", line 4, in <module>
    import ffmpeg_streaming
ModuleNotFoundError: No module named 'ffmpeg_streaming'
```

**Comment by Minims** [comment]
I have added the missing lib, it must be better now

**Comment by ScratMan** [comment]
Traceback (most recent call last):
  File "/app/main.py", line 17, in <module>
    from somfy_protect.websocket import SomfyProtectWebsocket
  File "/app/somfy_protect/websocket/__init__.py", line 12, in <module>
    from business.streaming.camera import VideoCamera
  File "/app/business/streaming/camera.py", line 4, in <module>
    import cv2
  File "/usr/local/lib/python3.11/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.11/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by birse29** [comment]
same issue

**Comment by Minims** [comment]
I have added the libGL in apt package. hope this is the last issue.

**Comment by ScratMan** [comment]
```
Traceback (most recent call last):
  File "/app/main.py", line 17, in <module>
    from somfy_protect.websocket import SomfyProtectWebsocket
  File "/app/somfy_protect/websocket/__init__.py", line 12, in <module>
    from business.streaming.camera import VideoCamera
  File "/app/business/streaming/camera.py", line 4, in <module>
    import cv2
  File "/usr/local/lib/python3.11/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.11/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by Minims** [comment]
new version available.

**Comment by ScratMan** [comment]
> new version available.

This one is working fine here. 👍
