### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by peluho** [Minims/SomfyProtect2MQTT#127]
Home Assistant 2023.9.3
Supervisor 2023.09.2
Installed in debian 12 aka bookworm

SomfyProtect2MQTT 
Current version: 2023.9.4

It was working perfectly, but it stop working after I upgrade to debian 12. I got an error saying that permission denied.

the config.yaml looks like this

```
somfy_protect:
  username: ****
  password: ****
  sites:
    - Home
homeassistant_config:
  code: false
  code_arm_required: false
  code_disarm_required: false
mqtt:
  host: 192.168.3.62
  port: 1883
  ssl: false
  username: ****
  password: ****
  client-id: somfy-protect
  topic_prefix: somfyProtect2mqtt
  ha_discover_prefix: homeassistant
delay_site: "10"
delay_device: "60"
manual_snapshot: false
debug: false
```

the log file:

```
[13:53:48] INFO: Image build
[13:53:48] INFO: starting original stuff...
2023-09-26 13:53:48,529 [INFO] [__main__:55] Starting SomfyProtect2Mqtt 2023.9.4
2023-09-26 13:53:48,529 [INFO] [root:41] Reading config file /usr/bin/SomfyProtect2MQTT/somfyProtect2Mqtt/config/config.yaml
2023-09-26 13:53:48,532 [INFO] [root:111] Init SSO
2023-09-26 13:53:48,532 [INFO] [somfy_protect.sso:76] Requesting Token
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f4d79f4a890>: Failed to establish a new connection: [Errno 13] Permission denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sso.myfox.io', port=443): Max retries exceeded with url: /oauth/oauth/v2/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4d79f4a890>: Failed to establish a new connection: [Errno 13] Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/SomfyProtect2MQTT/somfyProtect2Mqtt/main.py", line 59, in <module>
    SSO = init_sso(config=CONFIG)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/SomfyProtect2MQTT/somfyProtect2Mqtt/somfy_protect/sso/__init__.py", line 119, in init_sso
    token = sso.request_token()
            ^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/SomfyProtect2MQTT/somfyProtect2Mqtt/somfy_protect/sso/__init__.py", line 77, in request_token
    return self._oauth.fetch_token(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests_oauthlib/oauth2_session.py", line 341, in fetch_token
    r = self.request(
        ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests_oauthlib/oauth2_session.py", line 521, in request
    return super(OAuth2Session, self).request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sso.myfox.io', port=443): Max retries exceeded with url: /oauth/oauth/v2/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4d79f4a890>: Failed to establish a new connection: [Errno 13] Permission denied'))
[11:53:48] WARNING: Halt add-on
[11:53:48] INFO: Service restart after closing
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

if I look at the mosquito-broker, it seems like the client is unknown

```
2023-09-26 13:44:14: New connection from 172.30.32.2:49630 on port 1883.
2023-09-26 13:44:14: Client <unknown> closed its connection.
2023-09-26 13:46:14: New connection from 172.30.32.2:44872 on port 1883.
2023-09-26 13:46:14: Client <unknown> closed its connection.
2023-09-26 13:48:14: New connection from 172.30.32.2:51758 on port 1883.
2023-09-26 13:48:14: Client <unknown> closed its connection.
2023-09-26 13:50:14: New connection from 172.30.32.2:54660 on port 1883.
2023-09-26 13:50:14: Client <unknown> closed its connection.
2023-09-26 13:52:14: New connection from 172.30.32.2:56772 on port 1883.
2023-09-26 13:52:14: Client <unknown> closed its connection.
2023-09-26 13:54:14: New connection from 172.30.32.2:60156 on port 1883.
2023-09-26 13:54:14: Client <unknown> closed its connection.
2023-09-26 13:56:14: New connection from 172.30.32.2:55196 on port 1883.
2023-09-26 13:56:14: Client <unknown> closed its connection.
2023-09-26 13:58:14: New connection from 172.30.32.2:42120 on port 1883.
2023-09-26 13:58:14: Client <unknown> closed its connection.
```

if helps, from the iptables --list it's like trying to listen the 172.30.32.2:1883 but the one open is 172.30.32.0:1883. No idea if could be related to that.

```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy DROP)
target     prot opt source               destination         
DOCKER-USER  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (2 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             172.30.32.6          tcp dpt:http
ACCEPT     tcp  --  anywhere             172.30.33.0          tcp dpt:8884
ACCEPT     tcp  --  anywhere             172.30.33.0          tcp dpt:8883
ACCEPT     tcp  --  anywhere             172.30.33.0          tcp dpt:1884
ACCEPT     tcp  --  anywhere             172.30.33.0          tcp dpt:1883
ACCEPT     tcp  --  anywhere             172.30.33.3          tcp dpt:omniorb
ACCEPT     tcp  --  anywhere             172.30.33.3          tcp dpt:8086
ACCEPT     tcp  --  anywhere             172.30.33.7          tcp dpt:8485
ACCEPT     tcp  --  anywhere             172.30.33.8          tcp dpt:1627
ACCEPT     tcp  --  anywhere             172.30.33.9          tcp dpt:8555
ACCEPT     udp  --  anywhere             172.30.33.9          udp dpt:8555
ACCEPT     tcp  --  anywhere             172.30.33.9          tcp dpt:1984
ACCEPT     tcp  --  anywhere             172.30.33.6          tcp dpt:5000

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination         
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

```

**Comment by Minims** [comment]
I have change some values in the add-on, try to uninstall, update repo, and install again.

**Comment by peluho** [comment]
Ty I'm going to try in a while, I let you know what happens

**Comment by peluho** [comment]
> I have change some values in the add-on, try to uninstall, update repo, and install again.

Don't know what it was, but since your last modifications everything seems to work perfectly. Thank you for your support!

**Comment by Minims** [comment]
Here is the diff, will make this on the dev version too.
