### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by anthopocket** [Minims/SomfyProtect2MQTT#135]
Hi,

i doesn't have running the docker somfy2mqtt

the install docker is
docker run -d --name somfy2mqtt -v /var/www/html/plugins/docker2/data/config/configSomfy.yaml:/config minims/somfyprotect2mqtt

i have as errors :

2023-11-10T18:50:08.261161015Z 2023-11-10 18:50:08,261 [INFO] [__main__:55] Starting SomfyProtect2Mqtt 2023.11.0
2023-11-10T18:50:08.261321565Z 2023-11-10 18:50:08,261 [INFO] [root:41] Reading config file /config/config.yaml
2023-11-10T18:50:08.261420692Z 2023-11-10 18:50:08,261 [ERROR] [utils:43] File /config/config.yaml not found
2023-11-10T18:50:08.261498020Z 2023-11-10 18:50:08,261 [INFO] [root:111] Init SSO
2023-11-10T18:50:08.261579021Z Traceback (most recent call last):
2023-11-10T18:50:08.261604465Z   File "/app/main.py", line 59, in 
2023-11-10T18:50:08.261743474Z     SSO = init_sso(config=CONFIG)
2023-11-10T18:50:08.262410074Z           ^^^^^^^^^^^^^^^^^^^^^^^
2023-11-10T18:50:08.262434370Z   File "/app/somfy_protect/sso/__init__.py", line 112, in init_sso
2023-11-10T18:50:08.262565860Z     username = config.get("somfy_protect").get("username")
2023-11-10T18:50:08.263468578Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-10T18:50:08.263565431Z AttributeError: 'NoneType' object has no attribute 'get'

The config is ok with username and pwd.
config
---
# Somfy Protect APP credentials
somfy_protect:
  username: "xxxxx.xxxxx@gmail.com"
  password: "xxxxxxx"

  # Zones Label to check
  sites:
    - Maison

# Home Assistant Configuration
homeassistant_config:
  # Code to arm/disarm, Remove code to disable.
  code: 1234
  # Use Code on arm/disarm
  code_arm_required: false
  code_disarm_required: true

# MQTT Configuration
mqtt:
  host: 192.168.1.77
  port: 1883  # prefer SSL port if you can (not managed for now)
  username: admin
  password: "anthony"
  client-id: somfy-protect
  topic_prefix: "somfyProtect2mqtt"
  ha_discover_prefix: "homeassistant"

# SomfyProtect2MQTT
delay_site: 10  # seconds
delay_device: 60  # seconds
manual_snapshot: false

thanks you for you help

**Comment by Minims** [comment]
hello,


 try to rename `configSomfy.yaml` in `config.yaml`
 
 then run 
 ```
docker run -v /var/www/html/plugins/docker2/data/config:/config minims/somfyprotect2mqtt
```
