### ISSUE TITLE
Problème pour obtenir la liste des devices

### ISSUE THREAD

**Issue by Dwarfy27950** [Minims/SomfyProtect2MQTT#145]
Bonjour,
J'ai installé la version Docker de somfyprotect2mqtt et j'ai une erreur en boucle.
Voici le log, avec debug à true:

```
2024-01-09 10:13:07,169 [INFO] [__main__:62] Starting SomfyProtect2Mqtt 2023.12.2
2024-01-09 10:13:07,171 [INFO] [root:41] Reading config file /config/config.yaml
2024-01-09 10:13:07,193 [INFO] [root:111] Init SSO
2024-01-09 10:13:07,195 [INFO] [somfy_protect.sso:76] Requesting Token
2024-01-09 10:13:08,220 [INFO] [root:91] Init MQTT
2024-01-09 10:13:08,230 [INFO] [root:40] Init SomfyProtect2Mqtt
2024-01-09 10:13:08,238 [INFO] [somfy_protect.sso:76] Requesting Token
--- request header ---
2024-01-09 10:13:08,860 [DEBUG] [websocket:71] --- request header ---
GET /events/websocket?token=*** HTTP/1.1
Upgrade: websocket
Host: websocket.myfox.io
Origin: https://websocket.myfox.io
Sec-WebSocket-Key: 8S3FMxKpdeS38UT6VtdXOg==
Sec-WebSocket-Version: 13
Connection: Upgrade


2024-01-09 10:13:08,861 [DEBUG] [websocket:72] GET /events/websocket?token=*** HTTP/1.1
Upgrade: websocket
Host: websocket.myfox.io
Origin: https://websocket.myfox.io
Sec-WebSocket-Key: 8S3FMxKpdeS38UT6VtdXOg==
Sec-WebSocket-Version: 13
Connection: Upgrade


-----------------------
2024-01-09 10:13:08,863 [DEBUG] [websocket:73] -----------------------
--- response header ---
2024-01-09 10:13:08,865 [DEBUG] [websocket:94] --- response header ---
HTTP/1.1 101 Switching Protocols
2024-01-09 10:13:08,887 [DEBUG] [websocket:94] HTTP/1.1 101 Switching Protocols
Date: Tue, 09 Jan 2024 10:13:08 GMT
2024-01-09 10:13:08,889 [DEBUG] [websocket:94] Date: Tue, 09 Jan 2024 10:13:08 GMT
Connection: upgrade
2024-01-09 10:13:08,891 [DEBUG] [websocket:94] Connection: upgrade
Upgrade: websocket
2024-01-09 10:13:08,893 [DEBUG] [websocket:94] Upgrade: websocket
Sec-WebSocket-Accept: 3TjAg86hnAtacS7fzzaA+lMEyVI=
2024-01-09 10:13:08,895 [DEBUG] [websocket:94] Sec-WebSocket-Accept: 3TjAg86hnAtacS7fzzaA+lMEyVI=
-----------------------
2024-01-09 10:13:08,897 [DEBUG] [websocket:94] -----------------------
Websocket connected
2024-01-09 10:13:08,899 [INFO] [websocket:89] Websocket connected
2024-01-09 10:13:08,902 [INFO] [somfy_protect.websocket:129] Opened connection
2024-01-09 10:13:08,911 [INFO] [somfy_protect_2_mqtt:63] Found 1 Site(s)
2024-01-09 10:13:08,912 [INFO] [somfy_protect_2_mqtt:65] Found Site : Maison
2024-01-09 10:13:08,914 [INFO] [somfy_protect_2_mqtt:67] Storing Site ID for Maison
++Rcv raw: b'\x81${"key":"websocket.connection.ready"}'
2024-01-09 10:13:08,952 [DEBUG] [websocket:94] ++Rcv raw: b'\x81${"key":"websocket.connection.ready"}'
++Rcv decoded: fin=1 opcode=1 data=b'{"key":"websocket.connection.ready"}'
2024-01-09 10:13:08,953 [DEBUG] [websocket:94] ++Rcv decoded: fin=1 opcode=1 data=b'{"key":"websocket.connection.ready"}'
2024-01-09 10:13:08,955 [INFO] [somfy_protect.websocket:89] Websocket Connection is READY
2024-01-09 10:13:09,916 [INFO] [business:36] Looking for Sites
2024-01-09 10:13:10,122 [INFO] [business:60] Scenarios Core for Maison => {'object': 'list', 'items': [{'trigger': 'mode_disarmed', 'description': '', 'rolling_shutter_action': 'none', 'light_action': 'none', 'gate_action': 'none', 'garage_door_action': 'none', 'sync_status': 'ok'}, {'trigger': 'smoke_detection', 'description': '', 'rolling_shutter_action': 'rolling_shutter_up', 'light_action': 'light_on_timed', 'gate_action': 'none', 'garage_door_action': 'none', 'sync_status': 'ok'}, {'trigger': 'outdoor_trespass', 'description': '', 'rolling_shutter_action': 'rolling_shutter_down', 'light_action': 'light_on_timed', 'gate_action': 'none', 'garage_door_action': 'none', 'sync_status': 'ok'}, {'trigger': 'indoor_trespass', 'description': '', 'rolling_shutter_action': 'rolling_shutter_down', 'light_action': 'light_on_timed', 'gate_action': 'none', 'garage_door_action': 'none', 'sync_status': 'ok'}, {'trigger': 'mode_armed', 'description': '', 'rolling_shutter_action': 'none', 'light_action': 'none', 'gate_action': 'none', 'garage_door_action': 'none', 'sync_status': 'ok'}, {'trigger': 'mode_partial', 'description': '', 'rolling_shutter_action': 'none', 'light_action': 'none', 'gate_action': 'none', 'garage_door_action': 'none', 'sync_status': 'ok'}]}
2024-01-09 10:13:10,179 [INFO] [business:62] Scenarios for Maison => {'object': 'list', 'items': None}
2024-01-09 10:13:10,245 [WARNING] [business:63] v4 => []
2024-01-09 10:13:10,246 [INFO] [business:76] Looking for Devices
Exception in thread Thread-2 (somfy_protect_loop):
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/main.py", line 31, in somfy_protect_loop
    somfy_protect_api.loop()
  File "/app/somfy_protect_2_mqtt.py", line 87, in loop
    ha_devices_config(
  File "/app/business/__init__.py", line 78, in ha_devices_config
    my_devices = api.get_devices(site_id=site_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/somfy_protect/api/__init__.py", line 325, in get_devices
    devices += [
               ^
  File "/app/somfy_protect/api/__init__.py", line 326, in <listcomp>
    Device(**d)
TypeError: Device.__init__() missing 1 required positional argument: 'update_available'
2024-01-09 10:13:11,242 [WARNING] [__main__:115] API is DEAD, restarting
```

J'ai besoin d'aide :(

**Comment by Minims** [comment]
Hello,

J'ai effacé ton token, il faut le retirer quand tu colles des logs.

1. tu as quoi comme devices sur ton alarme ? 
2. comment tu lances somfyProtect2mqtt
3. peux tu copier ton fichier de configuration sans les login/password.

**Comment by Dwarfy27950** [comment]
Je n'avais vu que mon token était en clear...
J'ai une alarme somfy de base avec sirènes, tableau de commande, centrale, détecteurs. J'ai aussi 3 caméras (2 internes et 1 externe) détectées dans HA maisimpossible à configurer vu que je n'ai pas le code d'appairage
Pour lancer somfyProtect2mqtt, je lance la version docker avec le fichier de configuration ci dessous (dans lesquels j'ai effacé les logins password
---
# Somfy Protect APP credentials
somfy_protect:
  username: "mail entre guillemets"
  password: "mot de passe entre guillements"

  # Zones Label to check
  sites:
    - Maison

# Home Assistant Configuration
homeassistant_config:
  # Code to arm/disarm, Remove code to disable.
  code: ####
  # Use Code on arm/disarm
  code_arm_required: false
  code_disarm_required: true

# MQTT Configuration
mqtt:
  host: 192.168.1.##
  port: 1883  # prefer SSL port if you can (not managed for now)
  username: #####
  password: #######
  client-id: somfy-protect
  topic_prefix: "somfyProtect2mqtt"
  ha_discover_prefix: "homeassistant"

# SomfyProtect2MQTT
delay_site: 10  # seconds
delay_device: 60  # seconds
manual_snapshot: false
streaming: mqtt # mqtt or go2rtc (go2rtc only work for the HA Addon)

# Logging
debug: true

**Comment by Dwarfy27950** [comment]
Dispo quand tu veux minims

**Comment by Dwarfy27950** [comment]
Pour info, je n'ai pas le kit de connectivité, pas de Tahoma, juste l'appli. Peut etre que du coup ca pourrais t'aider. Sinon si besoin : discord, whatsapp, sms. Je suis dispo

**Comment by Minims** [comment]
Pour le moment je ne vois pas pourquoi. peut être un soucis avec le version Docker , mais je ne l'ai jamais utilisé. 
Est ce que tu sais valider le fonctionnement en mode standalone sans docker.

Sinon retente en mode debug et copie la ligne de log :
```Devices Capabilities:```
elle va faire plusieurs lignes.

**Comment by Dwarfy27950** [comment]
Je n'ai pas cette ligne donc je vais tenter l'installation en mode manuel

**Comment by Dwarfy27950** [comment]
Alors je ne suis pas bon du tout en python, mais parfois je me documente et j'ai juste rajouté = "" à la ligne 64 du fichier model.py
Aucune idée des effets de bord, mais déjà main.py tourne.
Je continue de regarder

**Comment by Minims** [comment]
Je fais un patch pour le mettre a False par défaut et non "", ca ira, mais j'aurais bien aimé savoir quel équipement ne retourne pas cette donnée sur l'api Somfy.

**Comment by Minims** [comment]
Nouvelle image publiée. A tester.

**Comment by Dwarfy27950** [comment]
Image testée ce soir, l'API répond. Je n'ai juste pas les snapshot des caméras internes, je verrais ca plus tard, c'est à mon avis un problème de mon coté, car la caméra externe fonctionne.
Sinon, pour savoir quel(s) équipement(s) ne répond(ent) pas à la donnée, je suis à ta totale disposition pour faire des tests.
