### ISSUE TITLE
Failed to launch

### ISSUE THREAD

**Issue by olivier11026** [Minims/SomfyProtect2MQTT#151]
Hi, 
I try to setup it with docker run, my config file is created with the following parameters :

```
# Somfy Protect APP credentials
somfy_protect:
  username: "xxxxxxx@xxx"
  password: "xxxxxxxxxxxxx"

# Zones Label to check
  sites:
    - Maison

# Home Assistant Configuration
homeassistant_config:
  # Code to arm/disarm, Remove code to disable.
  code: 0000
  # Use Code on arm/disarm
  code_arm_required: false
  code_disarm_required: true

# MQTT Configuration
mqtt:
  host: a.b.c.d
  port: 1883
  username: mqtt
  password: "xxxxxxxxxxxxx"
  client-id: somfy-protect
  topic_prefix: "zigbee2mqtt"
  ha_discover_prefix: "homeassistant"

# SomfyProtect2MQTT
delay_site: 30
delay_device: 60
manual_snapshot: false
```

I run into this issue : 

```
2024-02-24 17:45:32,423 [INFO] [__main__:61] Starting SomfyProtect2Mqtt 2024.1.0
2024-02-24 17:45:32,425 [INFO] [root:41] Reading config file /config/config.yaml
2024-02-24 17:45:32,428 [INFO] [root:111] Init SSO
2024-02-24 17:45:32,429 [INFO] [somfy_protect.sso:76] Requesting Token
2024-02-24 17:45:33,087 [INFO] [root:91] Init MQTT
Traceback (most recent call last):
  File "/app/main.py", line 72, in <module>
    MQTT_CLIENT = init_mqtt(config=CONFIG, api=API)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mqtt/__init__.py", line 95, in init_mqtt
    mqtt_client = MQTTClient(config=mqtt_config, api=api)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mqtt/__init__.py", line 28, in __init__
    self.client.connect(config.get("host", "127.0.0.1"), config.get("port", 1883), 60)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
TimeoutError: timed out
```

HA and Zigbee2MQTT run on the same server with Homebridge.

Any idea ? 
Thank you for your help

**Comment by Minims** [comment]
Hello,

Can you check that inside your container your MQTT server is reacheable ?

**Comment by olivier11026** [comment]
Hello,
Thank you for your reply.
How can I check this ? I am not a container expert :-/
Thank you
I can switch in French if you prefer

**Comment by olivier11026** [comment]
Hello,

Just switch to this command docker run --net=host -v /home/xxxxxx/docker/homeAssistant/somfyprotect2mqtt:/config minims/somfyprotect2mqtt and now everything seems to be OK.
Thank you
