### ISSUE TITLE
Probléme Config

### ISSUE THREAD

**Issue by anthopocket** [Minims/SomfyProtect2MQTT#152]
Hi,

i have a problem with the config file.
i have create the file in 

/opt/SomfyProtect2mqtt/config.yaml

the container doese'nt run with the error.
`AttributeError: 'NoneType' object has no attribute 'get'
2024-02-26 20:56:20,456 [INFO] [__main__:61] Starting SomfyProtect2Mqtt 2024.1.0
2024-02-26 20:56:20,457 [INFO] [root:41] Reading config file /config/config.yaml
2024-02-26 20:56:20,457 [ERROR] [utils:43] File /config/config.yaml not found
2024-02-26 20:56:20,457 [INFO] [root:111] Init SSO
Traceback (most recent call last):
  File "/app/main.py", line 70, in <module>
    SSO = init_sso(config=CONFIG)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/somfy_protect/sso/__init__.py", line 112, in init_sso
    username = config.get("somfy_protect").get("username")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
`
![image](https://github.com/Minims/SomfyProtect2MQTT/assets/62506538/6f4e441f-f3d6-4f14-a023-5a651df7c32d)

thanks you

**Comment by Minims** [comment]
Hello,

What is the full command you use to start the `main.py` ?

**Comment by anthopocket** [comment]
ok i succecceed.
but the cde with docker run is

docker run -d --name SomfyMqtt -v /opt/SomfyProtect2Mqtt/config:/config minims/somfyprotect2mqtt

**Comment by anthopocket** [comment]
ok i succecceed.
but the cde with docker run is

docker run -d --name SomfyMqtt -v /opt/SomfyProtect2Mqtt/config:/config minims/somfyprotect2mqtt
