### ISSUE TITLE
what is Add config to <PATH-TO-CONFIG-FOLDER>

### ISSUE THREAD

**Issue by manjump** [Minims/SomfyProtect2MQTT#166]
Hi,
I want install with docker, so OK for:
`docker run -v /srv/dev-disk-by-uuid-17502927-0659-46e4-b066-8f35344387d4/Storage/somfyprotect2mqtt/config:/config minims/somfyprotect2mqtt`

but what means Add` config to <PATH-TO-CONFIG-FOLDER>` because I have this error:

2024-08-04 10:33:58,504 [INFO] [__main__:57] Starting SomfyProtect2Mqtt 2024.3.0
2024-08-04 10:33:58,504 [INFO] [root:42] Reading config file /config/config.yaml
2024-08-04 10:33:58,504 [ERROR] [utils:44] File /config/config.yaml not found
2024-08-04 10:33:58,504 [INFO] [root:112] Init SSO
Traceback (most recent call last):
  File "/app/main.py", line 66, in <module>
    SSO = init_sso(config=CONFIG)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/somfy_protect/sso/__init__.py", line 113, in init_sso
    username = config.get("somfy_protect").get("username")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Minims** [comment]
Hello,

Did you put the config file in the config folder with you configuration ?  it seems the file is not found:

```
File /config/config.yaml not found
```

it is supposed to be this file https://github.com/Minims/SomfyProtect2MQTT/blob/master/somfyProtect2Mqtt/config/config.yaml.example

with your own params.(login, passwd, etc.)

**Comment by manjump** [comment]
Merci Minims pour ton aide.
En fait il faut d'abord créer le dossier somfyProtect2MQTT/config.
Puis copier le fichier ci dessus,
et enfin executer la commande: `docker run -v /srv/dev-disk-by-uuid-17502927-0659-46e4-b066-8f35344387d4/Storage/somfyprotect2mqtt/config:/config minims/somfyprotect2mqtt` ??

**Comment by manjump** [comment]
Du coup que signifie ce warning stp:

2024-08-05 04:44:11,647 [INFO] [somfy_protect.websocket:73] WebSocket Close
2024-08-05 04:44:11,676 [INFO] [somfy_protect.websocket:133] Websocket on_close, status None => None
2024-08-05 04:44:11,677 [INFO] [somfy_protect.websocket:69] Running Forever
2024-08-05 04:44:12,209 [WARNING] [__main__:96] Websocket is DEAD, restarting
2024-08-05 04:44:12,209 [INFO] [somfy_protect.sso:77] Requesting Token
2024-08-05 04:44:12,986 [INFO] [websocket:89] Websocket connected
2024-08-05 04:44:12,986 [INFO] [somfy_protect.websocket:129] Opened connection
2024-08-05 04:44:13,082 [INFO] [somfy_protect.websocket:89] Websocket Connection is READY

Merci Minims

**Comment by Minims** [comment]
C'est le sous processus websocket qui sert a récupérer les évènements fourni par Somfy.
Le service n'est pas stable et il y a un arrêt/redemarrage automatique du websocket toutes les 30 minutes pour éviter de perdre des messages. Il peut aussi galèrer un peu au démarrage de l'addon. Mais c'est "normal".

**Comment by manjump** [comment]
Merci Minims.
