### ISSUE TITLE
Error deploying on docker

### ISSUE THREAD

**Issue by cedsib** [Minims/SomfyProtect2MQTT#33]
Hello,

I tried to deploy on Docker (rather than HomeAssistant because I don't know why but your Module seems to stop working, or not starting correctly on reboot, even if HA does not says so : alarm state stays on "UNKNOWN", and restarting the module manually corrects it).

So I deployed the container on docker.
I pasted my config.yaml (the same that was workign on HA).

And I get this message :

```
TypeError: '<' not supported between instances of 'str' and 'int'
2022-05-01 19:33:39,119 [INFO] Starting SomfyProtect2Mqtt
2022-05-01 19:33:39,120 [INFO] Reading config file config/config.yaml
2022-05-01 19:33:39,127 [INFO] Init SomfyProtect2Mqtt
Traceback (most recent call last):
  File "/usr/src/SomfyProtect2MQTT/somfyProtect2Mqtt/main.py", line 29, in <module>
    SOMFY_PROTECT = SomfyProtect2Mqtt(CONFIG)
  File "/usr/src/SomfyProtect2MQTT/somfyProtect2Mqtt/somfy_protect_2_mqtt.py", line 52, in __init__
    if self.delay_site < 10:
TypeError: '<' not supported between instances of 'str' and 'int'
```

What don't I do correctly ?

**Comment by Minims** [comment]
Hello, can you paste your config.yaml without the credentials ?
