### ISSUE TITLE
error: stopping application

### ISSUE THREAD

**Issue by manjump** [Minims/SomfyProtect2MQTT#92]
Bonjour,

Je viens de m'apercevoir dans HA que tout était inconnu. Ci dessous le log provenant du docker. Que cela signifie t il?

`2023-04-01 17:21:15,565 [INFO] [utils:75] Stopping Application
Exception ignored in: <module 'threading' from '/usr/local/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 1388, in _shutdown
2023-04-01 17:21:15,650 [WARNING] [mqtt:71] Unexpected MQTT disconnection. Will auto-reconnect
2023-04-01 17:21:15,650 [INFO] [mqtt:73] Reconnecting to MQTT
    lock.acquire()
  File "/app/utils/__init__.py", line 78, in close_and_exit
    sys.exit(code)
SystemExit: 0`

**Comment by Minims** [comment]
Hello,

tu utilises quelle version ? en l'état je sais pas trop te dire pkoi ca a crashé. Par sécurité tu peux activer le watchdog sur l'addon pour le redémarrer automatiquement si jamais il crash. Je vais essayer de voir d'ou ca peut venir tout de même.

**Comment by Minims** [comment]
This issue has been stale for 30 days - it will be closed within the next 7 days if not updated
